//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class green_16_dec
    {
        public int entryID { get; set; }
        public Nullable<sbyte> VendorID { get; set; }
        public Nullable<System.DateTime> lpep_pickup_datetime { get; set; }
        public Nullable<System.DateTime> lpep_dropoff_datetime { get; set; }
        public string store_and_fwd_flag { get; set; }
        public Nullable<sbyte> RatecodeID { get; set; }
        public Nullable<int> PULocationID { get; set; }
        public Nullable<int> DOLocationID { get; set; }
        public Nullable<sbyte> passenger_count { get; set; }
        public Nullable<double> trip_distance { get; set; }
        public Nullable<double> fare_amount { get; set; }
        public Nullable<double> extra { get; set; }
        public Nullable<double> mta_tax { get; set; }
        public Nullable<double> tip_amount { get; set; }
        public Nullable<double> tolls_amount { get; set; }
        public Nullable<double> ehail_fee { get; set; }
        public Nullable<double> improvement_surcharge { get; set; }
        public Nullable<double> total_amount { get; set; }
        public Nullable<sbyte> trip_type { get; set; }
        public Nullable<sbyte> payment_type { get; set; }
    }
}
