//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yellow_tripdata_2016_08
    {
        public int id { get; set; }
        public Nullable<int> C_VendorID { get; set; }
        public Nullable<System.DateTime> tpep_pickup_datetime { get; set; }
        public Nullable<System.DateTime> tpep_dropoff_datetime { get; set; }
        public Nullable<int> passenger_count { get; set; }
        public Nullable<double> trip_distance { get; set; }
        public Nullable<int> RatecodeID { get; set; }
        public string store_and_fwd_flag { get; set; }
        public Nullable<int> PULocationID { get; set; }
        public Nullable<int> DOLocationID { get; set; }
        public Nullable<int> payment_type { get; set; }
        public Nullable<double> fare_amount { get; set; }
        public Nullable<double> extra { get; set; }
        public Nullable<double> mta_tax { get; set; }
        public Nullable<double> tip_amount { get; set; }
        public Nullable<double> tolls_amount { get; set; }
        public Nullable<double> improvement_surcharge { get; set; }
        public Nullable<double> total_amount { get; set; }
    }
}
