//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stage_PUCount
    {
        public int TaxiZone { get; set; }
        public Nullable<int> count { get; set; }
    
        public virtual TaxiZone TaxiZone1 { get; set; }
    }
}
