//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxiZone
    {
        public int TaxiZoneID { get; set; }
        public string TaxiZoneName { get; set; }
        public string Borough { get; set; }
    
        public virtual Stage_PUCount Stage_PUCount { get; set; }
    }
}
